scss:
  config_file: "config/linters/scss.yml"
  exclude:
    - "app/assets/stylesheets/application.scss"
    - "app/assets/stylesheets/application.css.scss"

ruby:
  config_file: config/linters/ruby.yml
